### ISSUE TITLE
feature request: A progress bar for chunks of species being processed?

### ISSUE THREAD

**Issue by Rekyt** [EnquistLab/RTNRS#10]
Hi!

A little bit related to #8, I wonder if it would be useful to provide a progress bar (for example using the example [`progressr`](https://cran.r-project.org/package=progressr) package) to display the number of chunks that remain to processed.

I don't think progress bars always add so much information, but in the case of long and expansive computation that can help to see how much are left. One way to avoid possible slowdowns due to the update of the progress bar would be to trigger only if the number of chunks to be submitted was significant (like 15 chunks of 1000 species or so).

If you're interested, I could give it a try and submit a PR to implement it.

**Comment by bmaitner** [comment]
Great idea!  I think you're right, they often slow things down, but here the slow part is waiting for the API, and so I think it shouldn't have much of an impact on overall speed.  I took an initial stab at it using utils:::txtProgressBar() so that I didn't need to add any dependencies.  As I've written it, if a user submits more than 5000 names, a progress bar will be displayed that is updated after each batch of names is returned.

Let me know if you think this is reasonable, or if you have a better idea feel free to do a PR  :)

**Comment by Rekyt** [comment]
I think it works very well here and is a helpful indication when matching a huge number of species names.

Thank you for the quick implementation @bmaitner 👍
