### ISSUE TITLE
TNRS_sources out of date

### ISSUE THREAD

**Issue by Koalha** [EnquistLab/RTNRS#3]
Version 0.2.0 of the TNRS R package can use more than three sources (such as WFO), but the TNRS_sources() function still only returns the three sources available in version 0.1.0.

**Comment by bmaitner** [comment]
I think this issue was caused by the GUI and the R package hitting different version of the API (development vs production).  I think this should be aligned now. 

@ojalaquellueva, the API is currently returning 4 sources (wfo, wcvp, tropicos, usda), the documentation for the API lists 6 sources (tpl, gcc, ildis, tropicos, usda, ncbi), and the GUI seems to accept 0 sources as it seems to be down at the moment. Can you confirm that the 4 returned by the API are indeed the correct set of sources available at the moment?

**Comment by ojalaquellueva** [comment]
This is an old issue long since resolved. All TNRS API instances currently access three sources: wfo, wcvp, cact, and R package is hitting the TNRS API production version, as intended. See https://tnrs.biendata.org/sources/ for details of taxonomic sources and the versions accessed by the TNRS.
